### ISSUE TITLE
AutoHandle + reflect

### ISSUE THREAD

**Issue by creack** [docker-archive/go-redis-server#2]
Instead of having a 'AutoHandler' that reflects and store the methods in a map, wouldn't be easier to provide a default Handler that can be overridden by the user?

**Comment by klizhentas** [comment]
Yep, having a default handler that can be overridden is a good thing, especially that user can override only some methods, keeping everything else as "not implemented"

I would still keep the low level base handler for the following reasons:

## Allow low level handlers
- I'd still have the ability to define your own set of commands, not using reflection
- Provide efficient dispatch of commands in map in case if you'd have a lot of commands

## Reflection handlers 
- "AutoHandler" is an extension of low level handler that allows anyone to build own set of Redis-style commands
- I wanted to have reflection "AutoHandler" to be checked and  when the RegisterHandler is being registered, and not during the actual command processing
- We can also create RedisHandler that defines full set of Redis commands and can be overridden
